version: '2'
services:

  hugo:
    image: hugo.radio-t
    build: .
    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      HUGO_ENV: production
    volumes:
      - ./hugo:/srv/hugo
      - ./public:/srv/hugo/public

  updater:
    build: updater
    hostname: updater
    container_name: updater
    restart: always
    logging: *default_logging
    volumes:
      - /home/umputun/.ssh/id_rsa.pub:/home/app/.ssh/id_rsa.pub
      - /home/umputun/.ssh/id_rsa:/home/app/.ssh/id_rsa

  publisher:
    build: publisher
    hostname: publisher
    container_name: publisher 
    restart: always
    logging: *default_logging
    environment:
      PYTHONPATH: /srv/publisher
    volumes:
      - ./hugo:/srv/hugo
      - ./publisher:/srv/publisher

  
