tags:
  album: "Радио-Т"
  cover: "./hugo/static/images/covers/cover.png"
  artist: "Umputun, Bobuk, Gray, Ksenks"
  title: "Радио-Т ${episode_num}"
toc:
  first_mp3_chapter_name: "Вступление"
  max_episode_hours: 4
